import sqlite3
from songs_funcs import sorting_hat


"""Creation of DB and a cursor"""
conn = sqlite3.connect('songs.db')
cur = conn.cursor()

# """Deleting a table"""
# cur.execute("DROP TABLE eli_songs")

"""Creation of columns in DB"""
# cur.execute("""CREATE TABLE ramm_songs (
# id integer PRIMARY KEY,
# a_song TEXT,
# blue_button BOOLEAN NOT NULL CHECK (blue_button IN (0, 1)),
# red_button BOOLEAN NOT NULL CHECK (red_button IN (0, 1)),
# green_button BOOLEAN NOT NULL CHECK (green_button IN (0, 1)),
# orange_button BOOLEAN NOT NULL CHECK (orange_button IN (0, 1)),
# violet_button BOOLEAN NOT NULL CHECK (violet_button IN (0, 1)),
# pink_button BOOLEAN NOT NULL CHECK (pink_button IN (0, 1)),
# black_button BOOLEAN NOT NULL CHECK (black_button IN (0, 1))
#
# )""")


# conn.commit()
#
# conn.close()

songs = ['Herzelied - Wollt ihr das Bett in Flammen sehen?',
        'Herzelied - Der Meister',
        'Herzelied - Weißes Fleisch',
        'Herzelied - Asche zu Asche',
        'Herzelied - Seemann',
        'Herzelied - Du riechst so gut',
        'Herzelied - Das alte Leid',
        'Herzelied - Heirate mich',
        'Herzelied - Herzelied ',
        'Herzelied - Laichzeit',
        'Herzelied - Rammstein',
        'Sehnsucht - Sehnsucht',
        'Sehnsucht - Engel',
        'Sehnsucht - Tier',
        'Sehnsucht - Bestrafe mich',
        'Sehnsucht - Du hast',
        'Sehnsucht - Bück dich',
        'Sehnsucht - Spiel mit mir',
        'Sehnsucht - Klavier',
        'Sehnsucht - Alter Mann',
        'Sehnsucht - Eifersucht',
        'Sehnshucht - Küss mich (Fellfrosch)',
        'Mutter - Mein Herz Brennt',
        'Mutter - Links 2 3 4 ',
        'Mutter - Sonne',
        'Mutter - Ich Will',
        'Mutter - Feuer Frei!',
        'Mutter - Mutter',
        'Mutter - Spielhur',
        'Mutter - Zwitter ',
        'Mutter - Rein Raus',
        'Mutter - Adios',
        'Mutter - Nebel',
        'Reise, Reise - Reise, Reise',
        'Reise, Reise - Mein Teil',
        'Reise, Reise - Dalai Lama',
        'Reise, Reise - Keine Lust',
        'Reise, Reise - Los',
        'Reise, Reise - Amerika',
        'Reise, Reise - Moskau',
        'Reise, Reise - Morgenstern',
        'Reise, Reise - Stein um Stein',
        'Reise, Reise - Ohne Dich',
        'Reise, Reise - Amour',
        'Rosenrot - Benzin',
        'Rosenrot - Mann Gegen Mann',
        'Rosenrot - Rosenrot ',
        'Rosenrot - Spring',
        'Rosenrot - Wo Bist Du',
        'Rosenrot - Strib Nicht Vor Mir',
        'Rosenrot - Zerstören',
        'Rosenrot - Hilf Mir',
        'Rosenrot - Te Quiero Puta!',
        'Rosenrot - Feuer und Wasser',
        'Rosenrot - Ein Lied',
        'Liebe Ist Für Alle Da - Rammlied',
        'Liebe Ist Für Alle Da - Ich Tu Dir Weh',
        'Liebe Ist Für Alle Da - Waidmanns Heil',
        'Liebe Ist Für Alle Da - Haifisch',
        'Liebe Ist Für Alle Da - B***********',
        'Liebe Ist Für Alle Da - Frühling in Paris',
        'Liebe Ist Für Alle Da - Weiner Blut',
        'Liebe Ist Für Alle Da - Pussy',
        'Liebe Ist Für Alle Da - Liebe Ist Für Alle Da ',
        'Liebe Ist Für Alle Da - Mehr',
        'Liebe Ist Für Alle Da - Rotter Sand',
        'Liebe Ist Für Alle Da - Führe mich',
        'Liebe Ist Für Alle Da - Donaukinder',
        'Liebe Ist Für Alle Da - Halt',
        'Liebe Ist Für Alle Da - Rotter Sand (Orchester Version)',
        'Liebe Ist Für Alle Da - Liese',
        'Rammstein - Deutschland',
        'Rammstein - Radio',
        'Rammstein - Zeig Dich',
        'Rammstein - Ausländer ',
        'Rammstein - Sex',
        'Rammstein - Puppe',
        'Rammstein - Was Ich liebe',
        'Rammstein - Diamant',
        'Rammstein - Wiet Weg',
        'Rammstein - Tattoo',
        'Rammstein - Hallomann',
        'Singles - Das Modell',
        'Singles - Kokain',
        'Singles - Feuerräder',
        'Singles - Wilder Wein',
        'Singles - Gib mir deine Augen',
        'Singles - Vergiss uns nicht',
        'Singles - 5/4',
        'Singles - Halleluja ',
        'Singles - Stripped',
        'Unreleased/Concert - Schwarzes Glas',
        'Unreleased/Concert - Jeder Lacht',
        'Unreleased/Concert - Eisenmann',
        'Unreleased/Concert - Ramm 4',
        'Unreleased/Concert - Pet Semetary',
        'Skills In Pills - Children Of The Sun',
        'Skills In Pills - Cowboy',
        'Skills In Pills - Fat',
        'Skills In Pills - Fish On',
        'Skills In Pills - Golden Shower',
        'Skills In Pills - Home Sweet Home',
        'Skills In Pills - Ladyboy',
        'Skills In Pills - Praise Abort',
        'Skills In Pills - Skills In Pills',
        "Skills In Pills - That's my heart",
        'Skills In Pills - Yukon',
        'Frau & Mann - Ach so gern',
        'Frau & Mann - Allesfresser',
        'Frau & Mann - Blut',
        'Frau & Mann - Frau & Mann',
        'Frau & Mann - Ich weiß es nicht',
        'Frau & Mann - Knebel',
        'Frau & Mann - Mathematik',
        'Frau & Mann - Platz Eins',
        'Frau & Mann - Shlaf ein',
        'Frau & Mann - Steh auf',
        'Frau & Mann - Wer weiß das schon',
        'Fish On - G-Spot Michael',
        'Cover - Штиль',
        'Lindemann: solo - Ich hasse Kinder',
        'Lindemann: solo - Любимый город',
        'Emigrate - Always on my mind',
        'Zeit - Armee Der Tristen',
        'Zeit - Zeit',
        'Zeit - Schwarz',
        'Zeit - Giftig',
        'Zeit - Zick Zack',
        'Zeit - OK',
        'Zeit - Meine Tränen',
        'Zeit - Angst',
        'Zeit - Dicke Titten',
        'Zeit - Lügen',
        'Zeit - Adieu'
        ]

"""Function for sorting from the list """
sorting_hat(songs, conn, cur)


# conn.commit()
#
# conn.close()
